"""Refresh the public walkthrough assets from the local app's prepared examples."""

import json
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.fine_tuning import SYSTEM_INSTRUCTION
from app.policy import REVIEW_CRITERIA
from app.seed import curated_fixtures
from app.showcase import EXPLANATION, GOOD_BODY, REJECTION_REASONS, SCENARIOS, prepared_draft


def main():
    cases = {}
    for name in ("supported", "unsupported", "uncertain", "blocked"):
        request, draft = prepared_draft(name)
        cases[name] = {
            "request": request,
            "evidence": draft.evidence,
            "action": {
                "type": "send_email", "recipient": draft.recipient,
                "subject": draft.subject, "body": draft.body,
                "trusted_permission": {
                    "recipient": draft.recipient, "allowed": name != "blocked",
                    "scope": "Meeting and project summaries",
                    "notes": "Prepared recipient permission for this walkthrough",
                },
            },
        }
    samples = [
        {**item, "id": f"sample-{index}", "decision": item["label"],
         "source": "owner_curated_fixture", "reason_text": ""}
        for index, item in enumerate(curated_fixtures(), 1)
    ]
    data = {
        "scenarios": SCENARIOS, "cases": cases, "samples": samples,
        "reasons": REJECTION_REASONS, "correction": GOOD_BODY,
        "systemInstruction": SYSTEM_INSTRUCTION,
        "explanation": EXPLANATION,
        "reviewCriteria": REVIEW_CRITERIA,
    }
    (ROOT / "docs" / "sample-data.js").write_text(
        "// Generated by scripts/build_walkthrough.py\nwindow.REVIEW_DEMO = "
        + json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8",
    )
    shutil.copyfile(ROOT / "app" / "static" / "app.css", ROOT / "docs" / "style.css")
    shutil.copyfile(ROOT / "app" / "static" / "icon.svg", ROOT / "docs" / "icon.svg")


if __name__ == "__main__":
    main()
